Etpa\Domain\Page:
  type: entity
  table: page
  repositoryClass: Etpa\Infraestructure\Persistence\Doctrine\PageRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    title:
      type: string
      length: 250
    description:
      type: text
  manyToMany:
    pages:
      targetEntity: Etpa\Domain\Page
      joinTable:
        name: page_transitions
        joinColumns:
          source_id:
            referencedColumnName: id
        inverseJoinColumns:
          target_id:
            referencedColumnName: id
