Etpa\Domain\Story:
  type: entity
  table: page
  repositoryClass: Etpa\Infraestructure\Persistence\Doctrine\PageRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    title:
      type: string
      length: 250
    description:
      type: text
