Etpa\Domain\Story:
  type: entity
  table: story
  repositoryClass: Etpa\Infrastructure\Persistence\Doctrine\StoryRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    title:
      type: string
      length: 250
    description:
      type: text
  oneToOne:
    firstPage:
      cascade: ["persist"]
      targetEntity: Etpa\Domain\Page
      joinColumn:
        name: page_id
        referencedColumnName: id
