Etpa\Domain\Story:
  type: entity
  table: story
  repositoryClass: Etpa\Infrastructure\Persistence\Doctrine\StoryRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    title:
      type: string
      length: 250
    description:
      type: text
    status:
      type: integer
  oneToMany:
    pages:
      targetEntity: Etpa\Domain\Action
      mappedBy: story
